### ISSUE TITLE
Please add swap support

### ISSUE THREAD

**Issue by jacob019** [eupnea-linux/kernel#1]
Please add swap support to this kernel.

**Comment by jacob019** [comment]
Respectfully, that is not an absolute truth.  Not all chromebooks have eMMC.  Depending on the use case, swapping to slow storage may be better than having a process killed by the kernel OOM.  I appreciate your efforts on this project, and I understand your decision to decline the request.  For reference here, in case anyone else needs it, although swapping to the mtd device is not possible without the mtdswap module, file based swapping is supported, it just needs to be enabled first:
echo 1 > /proc/sys/vm/disk_based_swap

**Comment by jacob019** [comment]
Good points and good general advice.  The beauty of open source is that each user can customize it for their needs as they wish.  I have a good use case for swap.  Zram is insufficient.  I swap to MicroSD to avoid wearing out the eMMC.  It makes a big difference for me.  While I would prefer to be able to swap directly to the block device, I am able to mount it and use a swap file, good enough.  Thanks for taking your time to communicate with me and for maintaining and developing this awesome project.

**Comment by Apacelus** [comment]
Also, now thinking about it... I think the [mainline kernel](https://github.com/eupnea-linux/mainline-kernel) should support it ootb. Either build a eupnea image with it by using ``main.py --mainline`` or install the mainline kernel on an existing install with ``update-kernel --mainline``

**Comment by jacob019** [comment]
Thanks friend.  Unfortunately the mainline kernel had several issues on my hardware.
